### ISSUE TITLE
Local Debug Environment

### ISSUE THREAD

**Issue by MrKeon** [AngryTribble/Star-Trek-Attack-Wing-Utopia#190]
Hello 👋 , I am familiar with NodeJS, but not as familiar with Grunt and http-server. When I attempt to step through the Chrome browser debugger( when running locally), I get a 404 source not found. Are there some steps I am missing to enable source mapping? If not, I was thinking of looking into setting this up and writing some documentation on how to set it up.

**Comment by AngryTribble** [comment]
@catsgotmytongue 

any ideas here?

**Comment by MrKeon** [comment]
I think I figured out the source map issue and created a Pull Request [here](https://github.com/AngryTribble/Star-Trek-Attack-Wing-Utopia/pull/192). I tested locally and was able to step through the code in the Chrome Debug tools.

**Comment by catsgotmytongue** [comment]
@MrKeon I have not checked this repo in a long time, sorry.

I think your PR is a valid change so I approved it.
In the future when making an issue please use a more descriptive title that gets at the heart of the issue.

I have worked on angular and react applications in the past and this one was missing both build and debug processes and lacked a local development/debug environment that was easy to setup when I looked at it. I added the missing grunt file and the http-server package. However I'm open to making a better debug environment as well as doing a typescript or js-doc update to this code base.

The 'pattern' this app uses is a giant json object used as a lookup table that has functions defined all over the place and the massive size of certain files is a big problem for maintainability over time. Many things are half-thought solutions that work and not documented or used correctly ( like the OnePerShip function, it only works if you know how to call it correctly ). 

Time permitting I'd like to make the code base be easier to work on, I just don't always have the time or energy after my 40 hr a week job :).

**Comment by catsgotmytongue** [comment]
This issue is addressed in PR #192
