### ISSUE TITLE
Enterprise NX-01 will not equip the Federation Prototype card to its granted slot per the card text abilities.

### ISSUE THREAD

**Issue by AngryTribble** [AngryTribble/Star-Trek-Attack-Wing-Utopia#228]
> Selecting the new version of the Enterprise NX-01 displays an extra construction slot for equipping the Federation Prototype card, per the ship ability; however, it does not allow actually equipping that card to the slot.

It appears that the "U.S.S." restriction code is still overriding my code. - from discord

**Comment by Relequestual** [comment]
Fixed by #233
