### ISSUE TITLE
Primary URL change

### ISSUE THREAD

**Issue by Relequestual** [AngryTribble/Star-Trek-Attack-Wing-Utopia#46]
The URL
https://angrytribble.github.io/Star-Trek-Attack-Wing-Utopia/staw-utopia/index.html
results in a 404. This was previously the URL the service was found at, including URLs copied for saved fleets.
The new URL is https://angrytribble.github.io/Star-Trek-Attack-Wing-Utopia, removing the last path and file segments.
There should be a redirect to avoid the 404.

**Comment by catsgotmytongue** [comment]
Closed by PR #47

**Comment by catsgotmytongue** [comment]
just a tiny fix, we don't want a staw-utopia/staw-utopia/index.html in the build just a staw-utopia/index.html 

I added onto your fix here, with a couple of build enhancements in the gruntfile:
https://github.com/AngryTribble/Star-Trek-Attack-Wing-Utopia/pull/48

![image](https://user-images.githubusercontent.com/506072/213101599-96cb083d-47cd-4dad-8ecb-ba863fd1e61f.png)

**Comment by catsgotmytongue** [comment]
this should be closed in PR #48
