### ISSUE TITLE
Starship Construction Card Type

### ISSUE THREAD

**Issue by AngryTribble** [AngryTribble/Star-Trek-Attack-Wing-Utopia#5]
Need to create a new card type called: Starship Construction. 

- Need to create the "Hook" symbol and add it to the font file
- Need to create a slot on the ships for these cards to be equipped, i.e. Admirals and Ambassadors 
- These cards do not take any faction penalties. 

Card Rules Link:
https://i.imgur.com/bzVa962.png

**Comment by catsgotmytongue** [comment]
@AngryTribble I think I have this one figured out, go  ahead  and assign it to me if you can.

**Comment by AngryTribble** [comment]
There you go!
