### ISSUE TITLE
Federation filter now incorrectly shows Vulcan and Bajorean subfaction cards too...

### ISSUE THREAD

**Issue by PrudentAndorian** [AngryTribble/Star-Trek-Attack-Wing-Utopia#51]
Some cards only interact with specific factions (even specific sub-factions).  There was a benefit to the filter picking them out separately.

**Comment by catsgotmytongue** [comment]
can you describe this issue in more detail and provide an example of the issue preferably with screenshots and specific cards mentioned ?

**Comment by catsgotmytongue** [comment]
Perhaps there needs to be a way to include sub-factions or not. 
I made the wrong assumption that sub-factions should always be part of the prime faction.

**Comment by AngryTribble** [comment]
I don't seem to understand this issue fully. The rules state that all Bajoran and Vulcan cards fall into the Federation faction, however not all Federation cards can be equipped to Bajoran or Vulcan ships. This is still easily achievable with the way the sort function works currently.

**Comment by PrudentAndorian** [comment]
There are two reasons to put the filter back to only Fed or Ind ships... (admittedly weak, but not without some consideration)

1) People playing a faction pure game could still see "federation only" or "Independent only" cards, now there isn't a way to do that.
2) The list is already ungodly long; this shortens the lists.

If someone wants to see Federation, Bajoran and Vulcan at once, they can select all three checks just as easily.
