### ISSUE TITLE
Leyton (admiral)

### ISSUE THREAD

**Issue by PrudentAndorian** [AngryTribble/Star-Trek-Attack-Wing-Utopia#53]
Leyton should have the words FLEET ACTION: in bold instead of Action:

**Comment by Relequestual** [comment]
Nice to have you with us! Greatly enjoying Alliance! Only found it recently.
*gets to fixing*
Should this be true for both the [Captain and Admiral](https://github.com/search?q=repo%3AAngryTribble%2FStar-Trek-Attack-Wing-Utopia%20Leyton&type=code)?

An aside, you're welcome to send Pull Requests if you like, although I'm guessing you're just busy which is also fine. Wouldn't want to delay anything! 😁

**Comment by AngryTribble** [comment]
Pull request #55 fixed the wording on the Admiral Leyton card
