### ISSUE TITLE
Shuttlecraft Rules

### ISSUE THREAD

**Issue by PrudentAndorian** [AngryTribble/Star-Trek-Attack-Wing-Utopia#54]
Shuttlecraft cannot equip admirals, Utopia allows this.
Shuttlecraft cannot equip cards whose discounted cost is higher than 3, Utopia allows this.

**Comment by AngryTribble** [comment]
1) According to the updated 2017 core rule book shuttlecraft can now equip Admirals.
2) The 2017 core rule book states "You cannot equip cards to a Shuttlecraft with a cost of more than 3 SP (including face down cards)". This rule however does not specifically call out printed cost of the card, and this allows for cards to be discounted.
