### ISSUE TITLE
Dahar Master giving put Captain Skill increases to Kor, Kang, Koloth even when they do not have Dahar Master equipped. 

### ISSUE THREAD

**Issue by AngryTribble** [AngryTribble/Star-Trek-Attack-Wing-Utopia#83]

**Comment by MrKeon** [comment]
I found a fix for this where I added a utility function that checks if the current card has a Dahar Master Talent occupying it's talent spot. I have a local branch, but I am not sure if I have permission to push my branch to this repo. (I'm new to contributing to open source XD)

**Comment by AngryTribble** [comment]
Awesome!

I will go and take a look at it tomorrow! Thanks for the help!



Sent via the Samsung Galaxy S21+ 5G, an AT&T 5G smartphone



-------- Original message --------
From: MrKeon ***@***.***>
Date: 5/31/23 6:44 PM (GMT-05:00)
To: AngryTribble/Star-Trek-Attack-Wing-Utopia ***@***.***>
Cc: Jerry Brown ***@***.***>, Author ***@***.***>
Subject: Re: [AngryTribble/Star-Trek-Attack-Wing-Utopia] Dahar Master giving put Captain Skill increases to Kor, Kang, Koloth even when they do not have Dahar Master equipped. (Issue #83)


I found a fix for this where I added a utility function that checks if the current card has a Dahar Master Talent occupying it's talent spot. I have a local branch, but I am not sure if I have permission to push my branch to this repo. (I'm new to contributing to open source XD)

**Comment by MrKeon** [comment]
https://github.com/MrKeon/Star-Trek-Attack-Wing-Utopia/tree/fix-dahar-master-bug

**Comment by AngryTribble** [comment]
@MrKeon 

I have pushed your pull request and merged it, but it appears as if the bug is still lingering

![image](https://github.com/AngryTribble/Star-Trek-Attack-Wing-Utopia/assets/118921428/a178f0d2-e0ac-4e94-9f98-8751a221f1b2)

**Comment by MrKeon** [comment]
Interesting, I tried and it worked as expected. Have you cleared your browser cache for https://angrytribble.github.io/ ?

<img width="1057" alt="Screenshot 2023-06-03 at 8 21 52 PM" src="https://github.com/AngryTribble/Star-Trek-Attack-Wing-Utopia/assets/67989130/b9f5d450-0ec5-437f-8dfe-a919ecc81784">

**Comment by AngryTribble** [comment]
I did clear out my cache at the time, but your right it does appear to be working now
